SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE tyre_data CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE lap_data CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE result CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE race CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE driver CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE team CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE circuit CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE season CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE season (
  season_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year NUMBER(4) NOT NULL UNIQUE,
  CONSTRAINT chk_season_year CHECK (year BETWEEN 1950 AND 2100)
);

CREATE TABLE circuit (
  circuit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(80) NOT NULL UNIQUE,
  location VARCHAR2(80) NOT NULL,
  country VARCHAR2(60) NOT NULL,
  length_km NUMBER(5,3) NOT NULL,
  CONSTRAINT chk_circuit_length CHECK (length_km > 0)
);

CREATE TABLE team (
  team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name VARCHAR2(80) NOT NULL UNIQUE,
  base_country VARCHAR2(60)
);

CREATE TABLE driver (
  driver_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(80) NOT NULL,
  nationality VARCHAR2(60),
  team_id NUMBER,
  driver_code VARCHAR2(3) NOT NULL UNIQUE,
  CONSTRAINT fk_driver_team FOREIGN KEY (team_id) REFERENCES team(team_id),
  CONSTRAINT chk_driver_code CHECK (driver_code = UPPER(driver_code))
);

CREATE TABLE race (
  race_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id NUMBER NOT NULL,
  circuit_id NUMBER NOT NULL,
  race_name VARCHAR2(100) NOT NULL,
  race_date DATE NOT NULL,
  weather VARCHAR2(30) DEFAULT 'Dry' NOT NULL,
  track_condition VARCHAR2(30) DEFAULT 'Green' NOT NULL,
  CONSTRAINT fk_race_season FOREIGN KEY (season_id) REFERENCES season(season_id),
  CONSTRAINT fk_race_circuit FOREIGN KEY (circuit_id) REFERENCES circuit(circuit_id),
  CONSTRAINT uq_race UNIQUE (season_id, circuit_id),
  CONSTRAINT chk_race_weather CHECK (weather IN ('Dry', 'Cloudy', 'Wet', 'Mixed')),
  CONSTRAINT chk_track_condition CHECK (track_condition IN ('Green', 'Rubbered', 'Damp', 'Wet'))
);

CREATE TABLE result (
  result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id NUMBER NOT NULL,
  driver_id NUMBER NOT NULL,
  team_id NUMBER NOT NULL,
  position NUMBER(2),
  points NUMBER(5,2),
  status VARCHAR2(30) DEFAULT 'Finished' NOT NULL,
  total_time_sec NUMBER(9,3),
  CONSTRAINT fk_result_race FOREIGN KEY (race_id) REFERENCES race(race_id),
  CONSTRAINT fk_result_driver FOREIGN KEY (driver_id) REFERENCES driver(driver_id),
  CONSTRAINT fk_result_team FOREIGN KEY (team_id) REFERENCES team(team_id),
  CONSTRAINT uq_result_driver_race UNIQUE (race_id, driver_id),
  CONSTRAINT chk_result_position CHECK (position IS NULL OR position > 0),
  CONSTRAINT chk_result_points CHECK (points >= 0)
);

CREATE TABLE lap_data (
  lap_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id NUMBER NOT NULL,
  driver_id NUMBER NOT NULL,
  lap_number NUMBER(3) NOT NULL,
  sector1_sec NUMBER(7,3),
  sector2_sec NUMBER(7,3),
  sector3_sec NUMBER(7,3),
  lap_time_sec NUMBER(8,3) NOT NULL,
  speed_kmph NUMBER(6,2),
  recorded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_lap_race FOREIGN KEY (race_id) REFERENCES race(race_id),
  CONSTRAINT fk_lap_driver FOREIGN KEY (driver_id) REFERENCES driver(driver_id),
  CONSTRAINT uq_lap_driver_race UNIQUE (race_id, driver_id, lap_number),
  CONSTRAINT chk_lap_number CHECK (lap_number > 0),
  CONSTRAINT chk_lap_times CHECK (
    (sector1_sec IS NULL OR sector1_sec > 0) AND
    (sector2_sec IS NULL OR sector2_sec > 0) AND
    (sector3_sec IS NULL OR sector3_sec > 0) AND
    lap_time_sec > 0
  )
);

CREATE TABLE tyre_data (
  tyre_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id NUMBER NOT NULL,
  driver_id NUMBER NOT NULL,
  stint_no NUMBER(2) NOT NULL,
  compound VARCHAR2(20) NOT NULL,
  start_lap NUMBER(3) NOT NULL,
  end_lap NUMBER(3) NOT NULL,
  CONSTRAINT fk_tyre_race FOREIGN KEY (race_id) REFERENCES race(race_id),
  CONSTRAINT fk_tyre_driver FOREIGN KEY (driver_id) REFERENCES driver(driver_id),
  CONSTRAINT uq_tyre_stint UNIQUE (race_id, driver_id, stint_no),
  CONSTRAINT chk_tyre_compound CHECK (compound IN ('Soft', 'Medium', 'Hard', 'Intermediate', 'Wet')),
  CONSTRAINT chk_tyre_laps CHECK (start_lap > 0 AND end_lap >= start_lap)
);

CREATE INDEX idx_driver_team ON driver(team_id);
CREATE INDEX idx_result_team ON result(team_id);
CREATE INDEX idx_race_season ON race(season_id);
CREATE INDEX idx_lap_race_driver ON lap_data(race_id, driver_id);
CREATE INDEX idx_result_race_position ON result(race_id, position);

CREATE OR REPLACE VIEW vw_race_results AS
SELECT
  s.year,
  r.race_name,
  c.name AS circuit_name,
  d.driver_code,
  d.name AS driver_name,
  t.team_name,
  res.position,
  res.points,
  res.status,
  res.total_time_sec
FROM result res
JOIN race r ON r.race_id = res.race_id
JOIN season s ON s.season_id = r.season_id
JOIN circuit c ON c.circuit_id = r.circuit_id
JOIN driver d ON d.driver_id = res.driver_id
JOIN team t ON t.team_id = res.team_id;

CREATE OR REPLACE VIEW vw_lap_performance AS
SELECT
  r.race_name,
  d.driver_code,
  d.name AS driver_name,
  l.lap_number,
  l.sector1_sec,
  l.sector2_sec,
  l.sector3_sec,
  l.lap_time_sec,
  l.speed_kmph
FROM lap_data l
JOIN race r ON r.race_id = l.race_id
JOIN driver d ON d.driver_id = l.driver_id;
